redis:
  container_name: afuri-redis
  image: redis
  ports:
    - "6379:6379"
postgres:
  container_name: afuri-postgres
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=afuri
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=afuri
mongo:
  container_name: aufuri-mongo
  image: mongo
  ports:
    - "27017:27017"
  environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=afuri
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
